### ISSUE TITLE
Add documentation for datasource provisioning

### ISSUE THREAD

**Issue by klagroix** [scalyr/scalyr-grafana-datasource-plugin#109]
Grafana provides the option to provision datasources using yaml config files: https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources

Having documentation for this in the README, the [Scalyr docs](https://app.scalyr.com/solutions/grafana), or on the [Grafana Plugin page](https://grafana.com/grafana/plugins/sentinelone-dataset-datasource/) would be a nice to have.

I was able to get this working using the following yaml:

```
apiVersion: 1

datasources:
  - name: Dataset (Scalyr)
    uid: dataset
    type: sentinelone-dataset-datasource
    access: proxy
    orgId: 1
    version: 1
    editable: true
    jsonData:
      scalyrUrl: "https://app.scalyr.com/"
    secureJsonData:
      apiKey: "INSERTAPIKEYHERE"
```
(Found `scalyrUrl` and  `apiKey` are the required key names by looking at this: https://github.com/scalyr/scalyr-grafana-datasource-plugin/blob/master/src/ConfigEditor.tsx)
